#:schema node_modules/wrangler/config-schema.json
name = "sublink-zhuanghuan"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "05981570c3f54ed8843b190b9b6207b9" }
]

[assets]
directory = "./public"
